spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/helios
    username: helios_admin
    password: 1234567890
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9094}
    producer:
    # Chave da mensagem
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer:  org.springframework.kafka.support.serializer.JsonSerializer
    topics:
      service-events: service-events

management:
  endpoints:
    web:
      exposure:
        include: prometheus, metrics
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: helios-observability
