services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=helios_admin
      - POSTGRES_PASSWORD=1234567890
      - POSTGRES_DB=helios
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql

  helios-api:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/helios
      SPRING_DATASOURCE_USERNAME: helios_admin
      SPRING_DATASOURCE_PASSWORD: 1234567890
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - postgres

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus_data:/prometheus
    depends_on:
      - helios-api

  grafana:
    image: grafana/grafana:latest
    container_name: helios-grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus

  kafka:
    image: apache/kafka:latest
    ports:
      - "9094:9094"
    environment:
      # Configurações obrigatórias para o modo SEM Zookeeper
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      # Ouvintes para comunicação interna (Docker) e externa (sua máquina)
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,EXTERNAL://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      # Outras configurações básicas
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    volumes:
      - ./kafka_data:/var/lib/kafka/data

  kafkaUi:
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8085:8080" # Acessível em http://localhost:8085
    environment:
      # Nome do cluster que aparecerá na interface da web
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: helios-cluster
      # Conexão interna do Docker apontando para o serviço do Kafka
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      - kafka

networks:
  default:
    external: true
    name: helios-network