{
 "title": "Helios-Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Services UP",
   "type": "stat",
   "description": "Services UP",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(helios_service_status == 1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Services DOWN",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(helios_service_status == 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Services",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(helios_service_status)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Services Timeline",
   "type": "state-timeline",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
   "targets": [
    { "expr": "helios_service_status", "legendFormat": "{{service}}" }
   ]
  },
  {
   "title": "Api Health Stats",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "jvm_memory_used_bytes{area=\"heap\"}",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Http Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count[1m])",
     "legendFormat": "{{uri}}"
    }
   ]
  }
 ]
}